### ISSUE TITLE
Microbit breaks off immediately after Pairing

### ISSUE THREAD

**Issue by jincanna** [yokobond/mbit-more-v2#14]
I installed the mircobit more module using xcratch. Then I tried pairing the microbit. However, it was cut off immediately after the pairing was successful. I installed the program again on microbit and tried it at Edge, not Chrome. but, microbit was not paired with microbit more. I'm not sure what the problem is. Can you help me?

**Comment by yokobond** [comment]
Did you clear "TILT TO FILL SCREEN", the calibration task for compass?
ref: [How to Use Microbit More](https://microbit-more.github.io/docs/#/how-to-use)

If you post your micro:bit hardware version and OS of PC, detail of process sequence for the fail cace, I could say more for resolving.

**Comment by jincanna** [comment]
Ooooo, That was the problem. Thank you so much!
