### ISSUE TITLE
micro:bit disconnecting

### ISSUE THREAD

**Issue by Steve-J** [yokobond/mbit-more-v2#15]
Hi, when I try to connect the microbit it connects but then instantly disconnects straight away. How can I fix this?

ありがとうございます
![000053-Microbit More and 16 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/12986342/176686637-ea65ee66-64e7-4505-aea2-d02d89d7772b.png)

**Comment by yokobond** [comment]
If you let us know the OS and browser version, we may be able to find the cause.

**Comment by Steve-J** [comment]
Hi, thanks for your reply. I managed to get it working. I had flashed the wrong firmware onto the micro:bit. However, I now have a problem where I can only catch two events. If I try to catch more than two the micro:bit disconnects. I have [this attachment](https://kitronik.co.uk/products/5644-game-controller) and I am trying to make it work in Scratch using your extension. Any ideas?

**Comment by yokobond** [comment]
That seems to be a problem specific to that device.
If you experience similar problems with other devices, etc., please post another Issue.
