### ISSUE TITLE
P0 is high block seems to respond in the wrong logic

### ISSUE THREAD

**Issue by mrhopeedu** [yokobond/mbit-more-v2#16]
Hi, when using the "P0 is high?" block, it does not look like it is reporting the correct logic. 
I would expect the block to return false when nothing is connected to the pin but it appeared to return true when "nothing" is connected to the pin. And it would return false when I actually connect up pin 0 to GND. 

That seems to be working opposite to the logic as in makecode. In Makecode, there's a block that says P0 is pressed. And that will only be true if P0 and GND is connected. I have attached screenshots of my code in MIcrobit More vs Makecode. Check out how the outcome differs. 

See the test in MicrobitMore: [https://i.imgur.com/ILfiijJ.png](url)
See the test in Makecode: [https://i.imgur.com/Hv0wjlO.png](url)

Thanks for looking into this, it's a great project!

**Comment by yokobond** [comment]
This behavior is intended to make this behavior closer to the behavior of the original LLK's Scratch micro:bit extension (https://scratch.mit.edu/microbit ).
In LLK's Scratch, the [when pin 0 connected] hat block is only executed when connected to GND.
MicroBitMore does not have this hat block, but to easily know when P0..3 is connected to GND, I set the default bias high.

You can use the [set pin P0 to input pull down] block to make it low when nothing is connected.

**Comment by mrhopeedu** [comment]
Thanks you Sir @yokobond for getting back to me on this, that clarifies the behaviour now.
However, with your suggestion, I tested it, does not seem to work accordingly. 

If I [set pin P0 to input pull down], it would correctly read it as low when nothing is connected but it does not toggle to high when something is connected.
The same is for [set pin 0 to input pull up], it would correctly read it as high when nothing is connected, but it won't toggle to low when something is connected.
However, if I use [set pin p0 to input none], it would then toggle when something is connected or not connected. 
See video demo and screenshot of my code.


It's not a big issue as if we use [set pin p0 to input none], thing will still work but just thought to inform you guys in case you need to know. 

https://user-images.githubusercontent.com/104048184/180356596-8f912270-f8fe-4278-860c-76e96c25db67.mp4

![Microbit-moreCode](https://user-images.githubusercontent.com/104048184/180356609-ab41361d-fe71-4f4e-bca0-84b15181b4c9.png)

**Comment by yokobond** [comment]
This blocks are working properly.
First, use a conductor to connect the terminals. Do not use fingers because the resistance is too high.
Then, connect GND for pull up and 3V for pull down to switch between high and low.
