### ISSUE TITLE
接続がすぐに切れてしまいます。　Connection drops out quickly.

### ISSUE THREAD

**Issue by boosuka** [yokobond/mbit-more-v2#18]
microbitをscratchに接続する際、デフォルトのmicrobitでは問題なく接続できるのですが、
microbit moreで接続しようとすると写真のようにすぐに接続が切れてしまいます。
使用しているmicrobitのバージョンはv2.21を使用しています。
インターフェースのバージョンは0257です。
何か解決策があれば教えてください。

When connecting a microbit to scratch, the default microbit connects fine, but when I try to connect with microbit more, the connection is immediately broken as shown in the picture.
The version of the microbit I am using is v2.21.
The version of the interface is 0257.
Please let me know if there is any solution to this problem.

![image](https://user-images.githubusercontent.com/112333266/187080748-f967ddbf-c474-4a14-a04c-7c97a9aaa762.png)

**Comment by madfire** [comment]
maybe you should flash the firmware onto the micro:bit [click here](https://github.com/microbit-more/pxt-mbit-more-v2/releases/download/0.2.4/microbit-mbit-more-v2-0_2_4.hex)

**Comment by boosuka** [comment]
I tried it, but the connection is immediately broken.
Please tell me other solution.

**Comment by boosuka** [comment]
Problem is soluted.
I missed the message "fill tile screen"
