### ISSUE TITLE
When connecting via USB, disconnecting will cause the browser page to crash.

### ISSUE THREAD

**Issue by Evolution-detector** [yokobond/mbit-more-v2#19]
Scratch3 - micro:bit more When connecting to a micro:bit via USB, disconnecting it, including selecting "Disconnect" in the interface or simply unplugging the micro:bit from the computer, will crash the current page.
Refreshing the page will bring you back to Scratch3, but may result in the last few steps in your work not being saved.
![image](https://user-images.githubusercontent.com/64944480/188395534-5a3530bb-6854-45f2-a9c6-2dd30e9623a6.png)
Latest version of Google Chrome
Firmware version V0.2.3
micro:bit board version V2.00

**Comment by yokobond** [comment]
The serial port was incorrectly closed.
This was fixed at 94f37a5f38f361a25a7363e8414efe7a42d89766  and released [Release 0\.2\.5 · microbit\-more/mbit\-more\-v2](https://github.com/microbit-more/mbit-more-v2/releases/tag/0.2.5).
