### ISSUE TITLE
How does the Scratch editor implement block area folding?

### ISSUE THREAD

**Issue by Evolution-detector** [yokobond/mbit-more-v2#22]
Hello, esteemed author.
I really like to use your micro:bit more extension. In the demo page you provided, I found an excellent feature: unlike MIT Scratch, the blocks section of your editor can be automatically collapsed and displayed fully again when the mouse is moved over the blocks. After using it for a while, I found that this collapse feature does not make dragging operation difficult, but very smooth and convenient.
I would like to ask you how this feature is implemented?
![image](https://user-images.githubusercontent.com/64944480/197722627-2ea533d4-d0e6-436d-a085-8c33dbd72d1f.png)

**Comment by yokobond** [comment]
This feature is implemented in [Xcratch](https://xcratch.github.io/), on which MicroBitMore is based.
Xcratch achieves the folding by modifying the css of the original LLK/scratch-gui.
