### ISSUE TITLE
DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope'

### ISSUE THREAD

**Issue by yusakuxxu** [yokobond/mbit-more-v2#9]
### Expected Behavior

Microbit More v2 が読み込まれ、画像のように Scratch Link ではなく、WebBluetooth を用いた接続が表示される

![image](https://user-images.githubusercontent.com/57650120/110941086-1dda6480-837b-11eb-893d-4b530fdbd0de.png)

### Actual Behavior

README の「Install into selfbuild Scratch3」に沿ってMicrobit More v2 をインストールしようとしました。
拡張機能読み込み時に、以下のようなエラーを表示し、表示がされません。

```
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://yokobond.github.io/mbit-more-v2/dist/microbitMore.mjs' failed to load.
```

### Steps to Reproduce

2021-03-12付け

1. LLK/scratch-gui を git clone ( --depth=1 )
2. LLK/scratch-vm を git clone ( --depth=1 )
3. scratch-vm を scratch-gui に link し、2つで起動することを確認
3. mbit-more-v2 を zip形式でダウンロード
4. zipを解凍したフォルダを名前変更し、scratch-gui と同じ階層に配置
5. mbit-more-v2 に移動後、以下のコマンドを実行
```
mbit-more-v2$ node ./scripts/install.js --id="microbitMore" --gui="../scratch-gui" --vm="../scratch-vm"
copy dir scratch/mbit-more-v2/src/block -> scratch/scratch-vm/src/extensions/microbitMore
copy dir scratch/mbit-more-v2/src/entry -> scratch/scratch-gui/src/lib/libraries/extensions/microbitMore
Registered in manager: microbitMore
Added to extrnsion list: microbitMore
stdout:
```
6. 実行後、一覧に表示はされます
![image](https://user-images.githubusercontent.com/57650120/110943865-0dc48400-837f-11eb-9881-e8a67e7e7974.png)
7. 拡張機能を読み込もうとすると、以下のエラーと共にscratchの画面に戻り、拡張機能は追加されていません。

```
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://yokobond.github.io/mbit-more-v2/dist/microbitMore.mjs' failed to load.
```

### Operating System and Browser

- Windows 10 Home 2004, 19041.867
- Chrome 89.0.4389.82（Official Build） （64 ビット）

### コメント

エラーのとおり外部拡張機能の読み込みが正常動作していないことはわかるのですが、
importScript の何がエラーを起こしているのか自分ではわからない状態です。
お力を貸していただけないでしょうか？

**Comment by yusakuxxu** [comment]
「Setup Development Environment」でも同様のエラーが起こりますが、
実際の動作は少し異なります。

### Actual Behavior

起動時に、Microbit More が読み込まれています。

![image](https://user-images.githubusercontent.com/57650120/110947704-dad0bf00-8383-11eb-98b0-6a842d940ab1.png)

しかし、接続しようとしても WebBluetooth が表示されていません。

![image](https://user-images.githubusercontent.com/57650120/110947798-f3d97000-8383-11eb-9582-170a573e3971.png)

また、左下のボタンを押して拡張機能一覧を開き、再度 Microbit More を読み込もうとすると、このissue で挙げた同じエラーが表示されます。

```
Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://yokobond.github.io/mbit-more-v2/dist/microbitMore.mjs' failed to load.
```

### Steps to Reproduce

1. LLK/scratch-gui を git clone ( --depth=1 )
2. LLK/scratch-vm を git clone ( --depth=1 )
3. scratch-vm を scratch-gui に link し、2つで起動することを確認
4. mbit-more-v2 を zip形式でダウンロード
5. zipを解凍したフォルダを名前変更し、scratch-gui と同じ階層に配置
6. mbit-more-v2 に移動後、以下のコマンドを実行
```
mbit-more-v2$ yarn run setup:local
yarn run v1.22.5
$ node ./scripts/setup-local.js && npm run install:local
Already exists link: scratch/scratch-gui/node_modules/scratch-vm -> scratch/scratch-vm

> mbit-more-v2@0.2.1 install:local
> node ./scripts/install.js --link -C --id="microbitMore" --gui="../scratch-gui" && node ./scripts/change-logo.js --gui="../scratch-gui"

Make link: scratch/scratch-gui/node_modules/scratch-vm/src/extensions/microbitMore -> scratch/mbit-more-v2/src/block
Make link: scratch/scratch-gui/src/lib/libraries/extensions/microbitMore -> scratch/mbit-more-v2/src/entry
Registered in manager: microbitMore
Add as a core extension: microbitMore
Added to extrnsion list: microbitMore
stdout:
Overwrite scratch/scratch-gui/src/components/menu-bar/scratch-logo.svg
Patch scratch/mbit-more-v2/scripts/scratch-gui-logo.patch
Done in 1.92s

mbit-more-v2$ yarn run install:local
yarn run v1.22.5
$ node ./scripts/install.js --link -C --id="microbitMore" --gui="../scratch-gui" && node ./scripts/change-logo.js --gui="../scratch-gui"
Already exists link: scratch/scratch-gui/node_modules/scratch-vm/src/extensions/microbitMore -> scratch/mbit-more-v2/src/block
Already exists link: scratch/scratch-gui/src/lib/libraries/extensions/microbitMore -> scratch/mbit-more-v2/src/entry
Already registered in manager: microbitMore
Already added as a core extension: microbitMore
Already added to extrnsion list: microbitMore
fail scratch-gui-translation.patch
Overwrite scratch/scratch-gui/src/components/menu-bar/scratch-logo.svg
Fail patch scratch/mbit-more-v2/scripts/scratch-gui-logo.patch
Done in 0.72s.
```

**Comment by yokobond** [comment]
Web Bluetoothの機能は [yokobond/xcratch: Extendable Scratch3 Programming Environment](https://github.com/yokobond/xcratch) を利用しています。
Web Bluetoothを使うには、ベースのscratch-guiをxcratchにしてください。
```
git clone -b xcratch https://github.com/yokobond/scratch-gui.git
```

**Comment by yokobond** [comment]
'importScripts' のエラーは、LLK/scratch-gui, LLK/scratch-vm へプレインストールするときに必要なパッチがあたっていませんでした。
install.jsでパッチを当てるようにします。

**Comment by yokobond** [comment]
LLK/scratch-gui に install.js したときの 'importScripts' エラーを修正しました。
6e6b14f62ff6228df4cb8b9f9e185e2126f16f9c

**Comment by yusakuxxu** [comment]
`importScripts` のエラーが起こらないことをこちらでも確認しました。
早急な bug 対応ありがとうございます。

> 'importScripts' のエラーは、LLK/scratch-gui, LLK/scratch-vm へプレインストールするときに必要なパッチがあたっていませんでした。
> install.jsでパッチを当てるようにします。

また、WebBluetooth は xcratch ブランチが必要なこともわかりました。
README に追記等ありがとうございました 🙏

**Comment by yokobond** [comment]
インストール関係のスクリプトを変更しました。
install.js は register.js になって、引数も少し変わっています。
ご注意ください。
ac753b7a96f8023a5d078e03113ca1b8cba9ad8d
